### ISSUE TITLE
Saving Interval is a Time of Day Picker

### ISSUE THREAD

**Issue by ardalis** [artem78/AutoScreenshot#3]
**Describe the bug**

I want to set the interval to 5 minutes, not 12:05 AM.

**To Reproduce**

Download 1.4.1 and install. Try to choose an interval like 5 minutes. Trying to reduce hours to 0 cycles to 12.

**Expected behavior**

Hours goes to 0, Minutes to 5. No AM/PM.

**Screenshots**

![image](https://user-images.githubusercontent.com/782127/96603453-07474a00-12c2-11eb-9605-d82184a7fb1f.png)

**Version**

1.4.1

**Comment by artem78** [comment]
Re: [artem78/AutoScreenshot] Saving Interval is a Time of Day Picker (#3)



Thank you for report! It will be fixed soon in next release.

---------------------------------
20 октября 2020 г. 17:51:02 от Steve Smith notifications@github.com:




Describe the bug
I want to set the interval to 5 minutes, not 12:05 AM.
To Reproduce
Download 1.4.1 and install. Try to choose an interval like 5 minutes. Trying to reduce hours to 0 cycles to 12.
Expected behavior
Hours goes to 0, Minutes to 5. No AM/PM.
Screenshots

Version
1.4.1

**Comment by artem78** [comment]
Hello!

I added fix. Could you please test [this build](https://github.com/artem78/AutoScreenshot/files/5417145/autoscreenshot_test.zip) on your PC? Is your problem solved?

**Comment by artem78** [comment]
Hello.

I didn\`r recieved any reply from you, so I think this issue solved and I published new [1.4.2 release](https://github.com/artem78/AutoScreenshot/releases/tag/v1.4.2) with this fix.
