### ISSUE TITLE
Can't take correct screenshot on 4K monitor

### ISSUE THREAD

**Issue by nuthx** [artem78/AutoScreenshot#6]
When I use 4K monitor, it can't take a screenshot of correct resolution. Only topleft 2560x1440 can be taken and cut. I tried to run with my old 1080P monitor and 2K monitor, works perfectly on both.

Screenshot:

![17 38 55](https://user-images.githubusercontent.com/29234438/101467241-060ad300-397d-11eb-83de-f630e544c7c5.jpg)

Version: 1.5

**Comment by artem78** [comment]
You use very large display. What is your screen resolution in pixels?

Could you please run [this test build](https://github.com/artem78/AutoScreenshot/files/5654666/autoscreenshot_multiple_monitor_test_build.zip)? I made it for another issue, but seems that it may have an impact also in your case.

**Comment by nuthx** [comment]
It's 3840x2160, standard 4K resolution. I have tried that build yesterday, but still not works.

**Comment by artem78** [comment]
3) Run this test and paste output here - [ScreenTest.zip](https://github.com/artem78/AutoScreenshot/files/5674221/ScreenTest.zip).

**Comment by nuthx** [comment]
Thanks, I'll try this and give you config file next Monday. Only my work place has the 4K monitor.

**Comment by nuthx** [comment]
1. config.ini:
[main]
OutputDir=D:\OneDrive\ͼƬ\Daily
ImageFormat=JPG
JPEGQuality=80
ColorDepth=24
Language=en
Grayscale=0
StartMinimized=1
StartCaptureOnStartUp=1
StopWhenInactive=0
AutoRun=1
FileNameTemplate=%Y-%M-%D\%H.%N.%S

2. All four formats don't work.

3. GetSystemMetrics(SM_CXVIRTUALSCREEN) GetSystemMetrics(SM_CYVIRTUALSCREEN) = 2560 1440
Screen.Width Screen.Height = 2560 1440
GetClientRect = 0 0 591 332
GetSystemMetrics(SM_XVIRTUALSCREEN) GetSystemMetrics(SM_YVIRTUALSCREEN) = 0 0
DesktopRect = 0 0 2560 1440
WorkAreaRect = 0 0 2560 1400
PPI = 96
Bitmap.Width Bitmap.Height = 2560 1440

It looks the screen test tool shows the wrong result. For reference, display resolution is 3840x2160 and do 150% scale on system setting.

**Comment by artem78** [comment]
150% scale on system settingQuite possibly that it may be a reason, because 2560x1400 * 1,5 = 3840x2160. Could you please make screenshot of your display settings, please? 14.12.2020, 05:45, "NuthX" <notifications@github.com>: config.ini:[main]OutputDir=D:\OneDrive\ͼƬ\DailyImageFormat=JPGJPEGQuality=80ColorDepth=24Language=enGrayscale=0StartMinimized=1StartCaptureOnStartUp=1StopWhenInactive=0AutoRun=1FileNameTemplate=%Y-%M-%D%H.%N.%SAll four formats don't work.GetSystemMetrics(SM_CXVIRTUALSCREEN) GetSystemMetrics(SM_CYVIRTUALSCREEN) = 2560 1440Screen.Width Screen.Height = 2560 1440GetClientRect = 0 0 591 332GetSystemMetrics(SM_XVIRTUALSCREEN) GetSystemMetrics(SM_YVIRTUALSCREEN) = 0 0DesktopRect = 0 0 2560 1440WorkAreaRect = 0 0 2560 1400PPI = 96Bitmap.Width Bitmap.Height = 2560 1440It looks the screen test tool shows the wrong result. For reference, display resolution is 3840x2160 and do 150% scale on system setting.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by artem78** [comment]
Also I need to know your DPI. 14.12.2020, 05:45, "NuthX" <notifications@github.com>: config.ini:[main]OutputDir=D:\OneDrive\ͼƬ\DailyImageFormat=JPGJPEGQuality=80ColorDepth=24Language=enGrayscale=0StartMinimized=1StartCaptureOnStartUp=1StopWhenInactive=0AutoRun=1FileNameTemplate=%Y-%M-%D%H.%N.%SAll four formats don't work.GetSystemMetrics(SM_CXVIRTUALSCREEN) GetSystemMetrics(SM_CYVIRTUALSCREEN) = 2560 1440Screen.Width Screen.Height = 2560 1440GetClientRect = 0 0 591 332GetSystemMetrics(SM_XVIRTUALSCREEN) GetSystemMetrics(SM_YVIRTUALSCREEN) = 0 0DesktopRect = 0 0 2560 1440WorkAreaRect = 0 0 2560 1400PPI = 96Bitmap.Width Bitmap.Height = 2560 1440It looks the screen test tool shows the wrong result. For reference, display resolution is 3840x2160 and do 150% scale on system setting.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by artem78** [comment]
Could you please take screenshot of AutoScreenshot main window? I want to 
check if UI components look good/correct on your diplay.

**Comment by nuthx** [comment]
> Quite possibly that it may be a reason, because 2560x1400 * 1,5 = 3840x2160.

I think it's the reason. It could take a correct resolution screenshot as 1.0 scale.

Calculated PPI is 163.18. I didn't find a way to show actual DPI.

![20201215104429](https://user-images.githubusercontent.com/29234438/102161657-a9e70800-3ec2-11eb-91ee-788a628c9eb0.png)

![20201215104502](https://user-images.githubusercontent.com/29234438/102161660-ab183500-3ec2-11eb-99da-234309a8c143.png)

By the way, I guess you can scale you screen on setting and test this issue.

**Comment by artem78** [comment]
Thanks for screenshots you provided.

> I guess you can scale you screen on setting and test this issue.

I will try.

**Comment by rainlizard** [comment]
I downloaded this program today and have the same issue with scaling.
Using Windows 8.1, at 150% windows display scaling.

at 1440p resolution: screenshots are only 1707x960 (clipped to top left of screen)
at 1080p resolution: screenshots are only 1280x720 (clipped to top left of screen)

So the math checks out, it's a scaling bug. But it would be good if this is fixed, because to change windows scaling setting back and forth you have to sign out or restart windows which is very inconvenient.

**Comment by artem78** [comment]
> I downloaded this program today and have the same issue with scaling.

This problem happens when your scale is 150% or more. In this case Windows provides to the program incorrect sizes. bacause it imitates 96 DPI for program UI.

In theory I can make my program [**DPI Aware**.](https://docs.microsoft.com/ru-ru/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows#dpi-awareness-mode) But it will lead to remaking GUI for supporting different screen DPI. I think instead of this it will be better to migrate program to modern Delphi version where HighDPI is supported.

Unfortunately, at the moment I have no other ideas how to get correct values.

**Comment by nuthx** [comment]
Now I found a way to avoid this issue:
1. Right click AutoScreenshot and goto property
2. Goto compatibility, then click Change high DPI settings
3. Check Override high DPI scaling behavior
4. Enjoy

**Comment by delfer** [comment]
Confirming issue.
My display is 1920x1280 with a 150% scale. But AutoScreenshot detects it as 1280x853 and screenshots are clipped.
![2021-05-24 00 29 34](https://user-images.githubusercontent.com/3233181/119277256-41494780-bc27-11eb-8af7-d52fe6155bb4.png)

**Comment by artem78** [comment]
@delfer This is known issue, but unfortunatelly at the moment I can`t fix it (migrate to newer version of Delphi needed for this), Anyway thank you.

**Comment by xor2003** [comment]
What about to build with Lazarus?

**Comment by artem78** [comment]
> What about to build with Lazarus?

Yes, I didn't forget about Lazarus. It also has High DPI support and allow to fix this issue. But migration need much time.

However I started to port project to Lazarus for experiment. Looks good and it is possible that one of the next release will be made with Lazarus.

**Comment by artem78** [comment]
Fixed in v1.8

**Comment by Sumeng257** [comment]
> Now I found a way to avoid this issue:
> 
> 1. Right click AutoScreenshot and goto property
> 2. Goto compatibility, then click Change high DPI settings
> 3. Check Override high DPI scaling behavior
> 4. Enjoy

brilliant！I love you
